add searching with -s arg
IFilonov/Goondex pull request #1
Opened 2023-07-01 19:14 UTC by IFilonov

2023-07-03 19:54 UTC, DmitriyVTitov requested changes
Задание выполнено не полностью.
При оформлении следуйте рекомендациям: https://github.com/thinknetica/go_course_4/blob/master/00-docs/Recommendations-and-rules.MD

2023-07-03 19:54 UTC, DmitriyVTitov commented on part2/cmd/goondex/main.go
> +	"Goondex/part2/pkg/crawler/spider"
А где эти пакеты? Все абсолютно файлы должны быть в PR!

2023-07-03 19:54 UTC, DmitriyVTitov commented on part2/cmd/goondex/main.go
> +			log.Fatal(err)
`log.Fatal(err)` тут явно лишний.

2023-07-03 19:54 UTC, DmitriyVTitov commented on part2/cmd/goondex/main.go
> +}
По заданию результаты сканирования нужно объединить.

2023-07-04 18:09 UTC, IFilonov commented on part2/cmd/goondex/main.go
> +	"Goondex/part2/pkg/crawler/spider"
добавил предыдущими коммитами, думал так будет проще. Сделал сквош трех последних коммитов.

2023-07-04 18:09 UTC, IFilonov commented on part2/cmd/goondex/main.go
> +			log.Fatal(err)
Убрал, сделал сообщение.

2023-07-04 18:10 UTC, IFilonov commented on part2/cmd/goondex/main.go
> +}
Сделал слайс allDocs

2023-07-07 06:39 UTC, DmitriyVTitov approved these changes

2023-07-07 06:39 UTC, DmitriyVTitov commented on part2/cmd/goondex/main.go
> +}
Красиво, коротко, легко читается.

2023-07-09 05:28 UTC, merged