part5 save and read scan results
IFilonov/Goondex pull request #5
Opened 2023-07-11 09:23 UTC by IFilonov

2023-07-13 06:35 UTC, DmitriyVTitov requested changes

2023-07-13 06:35 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +	index "Goondex/part3/pkg"
Все файлы должны быть в ответе. Я не могу искать по вашим репозиториям пакеты.

2023-07-14 11:51 UTC, IFilonov commented on part5/cmd/main.go
> +	index "Goondex/part3/pkg"
Поправил ссылку на файл

2023-07-17 07:07 UTC, DmitriyVTitov requested changes
Я не могу в тридцати репозиториях переходить по ссылкам и смотреть код из разных мест.

2023-07-17 07:07 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +	"encoding/gob"
Все файлы ДЗ должны быть в ответе. Не должно быть импортов из других ДЗ.

2023-07-21 19:38 UTC, DmitriyVTitov requested changes
Ошибки очень важны в Go. Если внутри функции может случиться ошибка, то функция должна также возвращать ошибку, за очень редким исключением.
Любой ввод-вывод связан с потенциальными ошибками, поэтому функций, не возвращающих ошибку здесь просто не может быть.
Также ошибки никогда нельзя игнорировать.

2023-07-21 19:38 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +}
Жуть! Вы абсолютно уверены, что пользователя интересно читать стек вызовов?
Никогда не используйте панику! По крайней мере в ближайшие полгода.

2023-07-21 19:38 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +	}
Тут функции, работающие с файлами, и не может быть ошибки? Это невозможно.
Функция, работающая с вводом-выводом должна ВСЕГДА возвращать возможную ошибку последним значением. И вызывающий код должен ВСЕГДА её проверять.

2023-07-24 18:03 UTC, IFilonov commented on part5/cmd/main.go
> +}
Убрал panic

2023-07-24 18:03 UTC, IFilonov commented
> Ошибки очень важны в Go. Если внутри функции может случиться ошибка, то функция должна также возвращать ошибку, за очень редким исключением. Любой ввод-вывод связан с потенциальными ошибками, поэтому функций, не возвращающих ошибку здесь просто не может быть. Также ошибки никогда нельзя игнорировать.

2023-07-24 18:06 UTC, IFilonov commented on part5/cmd/main.go
> +	}
Обработал ошибку внутри функции. Получается, если, например, ошибка записи в файл, об этом сообщается клиенту, но это не критично, программа будет запускать сканирование каждый раз.

2023-07-27 11:25 UTC, DmitriyVTitov requested changes
Функции должны возвращать ошибки (если, конечно, ошибки возможны). А вызывающий код должен эти ошибки проверять и предпринимать какие-то действия.

2023-07-27 11:25 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +}
Ошибки игнорируются. Нельзя просто так взять, и забить на ошибку! Если она случилась, то функция должна ошибку вернуть.
Вот я захочу воспользоваться вашим пакетом и как мне догадываться: получилось что-то там прочитать-записать или нет?

2023-07-27 11:25 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +}
Вот эта функция просто завершает работу в случае ошибки. И как программист должен понять: удалось ей записать что-то или нет?

2023-07-29 10:11 UTC, DmitriyVTitov requested changes
Ошибки ОБЯЗАТЕЛЬНО надо обрабатывать, т.е. что-то делать. Ошибки меняют логику работы, а у вас они ни на что не влияют.

2023-07-29 10:11 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +	}
Реакцией на ошибку должно быть действие! Недостаточно что-то напечатать, эти сообщения на сервере никто читать не будет.

2023-07-29 10:11 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +	return str
не понимаю, для чего вот это?

2023-07-29 10:11 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +}
Избегайте указателей. У вас в нескольких функциях указатели на слайсы, в этом нет никакой необходимости.

2023-07-29 18:53 UTC, IFilonov commented on part5/cmd/main.go
> +	return str
Если строка пустая, то он превращается в nil

2023-07-29 18:53 UTC, IFilonov commented on part5/cmd/main.go
> +}
Убрал указатель здесь. В остальных происходит изменение передаваемого в параметре слайса.

2023-08-01 18:02 UTC, DmitriyVTitov approved these changes
ОК

2023-08-01 18:02 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +	return str
А зачем? Чем nil лучше пустой строки?

2023-08-01 18:02 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +	return str
Больше того: nil сильно хуже, потому что может вызывать панику.

2023-08-01 18:02 UTC, DmitriyVTitov commented on part5/cmd/main.go
> +	}
Можно точно также было проверить на пустую строку. Больше того, такая проверка имеет смысл в самом начале.

2023-08-01 18:41 UTC, merged