part6 change Geom to objet
IFilonov/Goondex pull request #6
Opened 2023-07-11 14:26 UTC by IFilonov

2023-07-13 06:41 UTC, DmitriyVTitov requested changes
Посмотрите на саму задачу. Разве нужно всё вот это для вычисления расстояния между двумя точками?

2023-07-13 06:41 UTC, DmitriyVTitov commented on part6/pkg/hw.go
> +	}
log.Fatal - зло, не надо использовать вообще :)

2023-07-13 06:41 UTC, DmitriyVTitov commented on part6/pkg/hw.go
> +}
Проблема кода в том, что он переусложнён. А вы делаете его ещё сложнее!

2023-07-26 05:35 UTC, IFilonov commented on part6/pkg/hw.go
> +}
Хотел сделать его еще более ООП )))

2023-07-27 11:35 UTC, DmitriyVTitov approved these changes

2023-07-27 11:35 UTC, DmitriyVTitov commented on part6/pkg/hw.go
> +	}
Вот это условие не имеет смысла. Почему я не могу вычислить расстояние с отрицательными координатами?
Пакет должен быть универсальный, а такие ограничения нужно проверять на стороне вызывающего кода.

2023-07-27 11:35 UTC, DmitriyVTitov commented on part6/pkg/hw.go
> +func CalculateDistance(X1, Y1, X2, Y2 float64) (float64, error) {
Такая функция в принципе не должна возвращать ошибки, откуда она возьмётся?

2023-07-27 18:34 UTC, merged