part11 tcp server client http scaner
IFilonov/Goondex pull request #8
Opened 2023-07-29 09:35 UTC by IFilonov

2023-07-29 11:01 UTC, DmitriyVTitov requested changes

2023-07-29 11:01 UTC, DmitriyVTitov commented on part11/pkg/netsrv/netsrv.go
> +		}
Нет, так не пойдёт. Как вы думаете, Яндекс сканирует весь Интернет при каждом запросе пользователя? Думаю, нет.
Надо просканировать сайты однажды и искать по ним.

2023-07-30 04:27 UTC, IFilonov commented on part11/pkg/netsrv/netsrv.go
> +		}
Да я чуть другое сделал, клиент передавал url, сервер отдавал содержимое. Переделал.

2023-08-01 18:09 UTC, DmitriyVTitov approved these changes
ОК, но структура пакетов должна быть иной. Не собирайте в пакете несвязанный код. Сканирование сайтов, поиск и обслуживание сетевых запросов имеют смысл по отдельности и не связанны. Посмотрите главу 21 книги "Чистая архитектура".

2023-08-01 18:09 UTC, DmitriyVTitov commented on part11/pkg/netsrv/netsrv.go
> +}
Пакет сетевой службы не должен занимать ни сканированием сайтов ни поиском. Он должен реализовать сетевую службу и всё!
Куда делся индекс и бинарный поиск? Когда я писал удалить всё лишнее, индекс не имелся ввиду :)
В общем, принимаю, но следует почитать про пакеты и как мы организовываем код в пакеты. Сканирование и поиск должны быть в своих пакетах.

2023-08-01 18:41 UTC, merged